(function(){
'use strict';
const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
const workspace=$('#workspace'),panel=$('#toolPanel'),status=$('#toolStatus');let activeTool='';
if(window.pdfjsLib) pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
$('#year').textContent=new Date().getFullYear();
$('#menuToggle').addEventListener('click',()=>$('.topbar').classList.toggle('menu-open'));
$('#toolSearch').addEventListener('input',filterTools);let currentFilter='all';
$$('.category').forEach(b=>b.addEventListener('click',()=>{$$('.category').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;filterTools()}));
function filterTools(){let q=$('#toolSearch').value.toLowerCase();$$('.tool-card').forEach(c=>{c.hidden=!(currentFilter==='all'||c.dataset.category===currentFilter)||!(c.innerText+' '+c.dataset.search).toLowerCase().includes(q)})}
$$('.tool-open').forEach(b=>b.addEventListener('click',()=>openTool(b.dataset.tool)));
$('#closeTool').addEventListener('click',()=>{workspace.hidden=true;activeTool='';panel.innerHTML='';status.textContent='';workspace.scrollIntoView({behavior:'smooth',block:'nearest'})});
const defs={
'pdf-excel':['PDF to Excel','Extract selectable PDF text into Excel cells. Table layouts may need cleanup.'],
'merge-pdf':['Merge PDF','Select two or more PDF files to combine them in order.'],
'split-pdf':['Split PDF','Choose a PDF and the page range you want to export.'],
'images-pdf':['Images to PDF','Choose JPG or PNG images to combine into a PDF.'],
'compress-image':['Image compressor','Compress an image in your browser and download the smaller file.'],
'percentage':['Percentage calculator','Calculate percentages, discounts, and percentage changes.'],
'word-counter':['Word counter','Paste or type text to count words and characters.']};
function openTool(id){activeTool=id;workspace.hidden=false;$('#workspaceTitle').textContent=defs[id][0];$('#workspaceDesc').textContent=defs[id][1];status.textContent='';status.className='status';panel.innerHTML=toolMarkup(id);wireTool(id);workspace.scrollIntoView({behavior:'smooth',block:'start'})}
function toolMarkup(id){switch(id){case'pdf-excel':return `<label for="file">Choose PDF file</label><input id="file" type="file" accept="application/pdf"><p class="hint">Creates a workbook with extracted text. Scanned PDFs need OCR, which is not included in this first version.</p><button class="convert-button" id="run">Convert to Excel (.xlsx)</button>`;
case'merge-pdf':return `<label for="files">Choose PDF files (select multiple in the order you want)</label><input id="files" type="file" accept="application/pdf" multiple><button class="convert-button" id="run">Merge PDFs</button>`;
case'split-pdf':return `<label for="file">Choose PDF file</label><input id="file" type="file" accept="application/pdf"><div class="field-row"><div><label for="from">First page</label><input id="from" type="number" min="1" value="1"></div><div><label for="to">Last page</label><input id="to" type="number" min="1" value="1"></div></div><button class="convert-button" id="run">Export selected pages</button>`;
case'images-pdf':return `<label for="files">Choose JPG or PNG images (multiple allowed)</label><input id="files" type="file" accept="image/jpeg,image/png" multiple><button class="convert-button" id="run">Create PDF</button>`;
case'compress-image':return `<label for="file">Choose image</label><input id="file" type="file" accept="image/*"><div class="field-row"><div><label for="quality">JPEG quality (0.2–1)</label><input id="quality" type="number" min="0.2" max="1" step="0.1" value="0.75"></div><div><label for="maxwidth">Maximum width (px)</label><input id="maxwidth" type="number" min="100" max="8000" value="1600"></div></div><button class="convert-button" id="run">Compress image</button>`;
case'percentage':return `<div class="field-row"><div><label for="num">What is the number?</label><input id="num" type="number" value="500"></div><div><label for="percent">Percentage (%)</label><input id="percent" type="number" value="10"></div></div><button class="convert-button" id="run">Calculate percentage</button><div id="calcResult" class="calc-result"></div><hr><label for="oldValue">Percentage change — old value</label><input id="oldValue" type="number" value="100"><label for="newValue">New value</label><input id="newValue" type="number" value="120"><button class="convert-button" id="changeCalc">Calculate change</button><div id="changeResult" class="calc-result"></div>`;
case'word-counter':return `<label for="textInput">Your text</label><textarea id="textInput" placeholder="Paste or type your text here…"></textarea><div class="counter-grid"><div><b id="words">0</b><span>Words</span></div><div><b id="chars">0</b><span>Characters</span></div><div><b id="charsNoSpace">0</b><span>Without spaces</span></div><div><b id="sentences">0</b><span>Sentences</span></div><div><b id="minutes">0</b><span>Reading minutes</span></div></div><button class="convert-button" id="copyText">Copy text</button>`;default:return ''}}
function wireTool(id){if(id==='percentage'){ $('#run').onclick=()=>{let n=Number($('#num').value),p=Number($('#percent').value);$('#calcResult').textContent=`${p}% of ${n} = ${fmt(n*p/100)}`};$('#changeCalc').onclick=()=>{let a=Number($('#oldValue').value),b=Number($('#newValue').value);$('#changeResult').textContent=a===0?'Percentage change is undefined when the old value is zero.':`Change: ${fmt(((b-a)/Math.abs(a))*100)}% (${fmt(b-a)} ${b>=a?'increase':'decrease'})`};$('#run').click();return}
if(id==='word-counter'){const update=()=>{let t=$('#textInput').value.trim(),words=t?t.split(/\s+/).length:0;$('#words').textContent=words;$('#chars').textContent=$('#textInput').value.length;$('#charsNoSpace').textContent=$('#textInput').value.replace(/\s/g,'').length;$('#sentences').textContent=(t.match(/[.!?]+(?=\s|$)/g)||[]).length;$('#minutes').textContent=words?Math.max(1,Math.ceil(words/200)):0};$('#textInput').addEventListener('input',update);$('#copyText').onclick=async()=>{try{await navigator.clipboard.writeText($('#textInput').value);setStatus('Text copied to clipboard.','success')}catch(e){setStatus('Clipboard access was blocked by your browser.','error')}};return}
$('#run').addEventListener('click',()=>runFileTool(id).catch(e=>{console.error(e);setStatus(e.message||'Something went wrong. Please check the file and try again.','error')}));}
function fmt(n){return Number(n.toFixed(4)).toLocaleString(undefined,{maximumFractionDigits:4})}
function setStatus(msg,type=''){status.textContent=msg;status.className='status '+type}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}
function getFile(id='file'){const f=$('#'+id)?.files?.[0];if(!f)throw new Error('Please choose a file first.');return f}
function safeName(s){return s.replace(/\.[^.]+$/,'').replace(/[^a-z0-9_-]+/gi,'-').slice(0,70)||'sheetpdf-output'}
async function runFileTool(id){const button=$('#run');button.disabled=true;setStatus('Working in your browser…');try{
if(id==='pdf-excel')await pdfToExcel();else if(id==='merge-pdf')await mergePdf();else if(id==='split-pdf')await splitPdf();else if(id==='images-pdf')await imagesToPdf();else if(id==='compress-image')await compressImage();}finally{button.disabled=false}}
async function pdfToExcel(){const f=getFile();if(!window.pdfjsLib||!window.XLSX)throw new Error('A conversion library did not load. Refresh the page and try again.');const bytes=await f.arrayBuffer(),pdf=await pdfjsLib.getDocument({data:bytes}).promise;const wb=XLSX.utils.book_new();let allRows=[];for(let i=1;i<=pdf.numPages;i++){setStatus(`Reading page ${i} of ${pdf.numPages}…`);const page=await pdf.getPage(i),content=await page.getTextContent();let items=content.items.filter(x=>x.str&&x.str.trim());let rows=[];let currentY=null,row=[];for(const it of items){let y=Math.round(it.transform[5]);if(currentY!==null&&Math.abs(y-currentY)>4){rows.push(row);row=[]}currentY=y;row.push({x:it.transform[4],text:it.str})}if(row.length)rows.push(row);const cells=[];for(const r of rows){r.sort((a,b)=>a.x-b.x);cells.push(r.map(x=>x.text.trim()).filter(Boolean))}if(cells.length){let ws=XLSX.utils.aoa_to_sheet(cells);XLSX.utils.book_append_sheet(wb,ws,`Page ${i}`)}allRows.push(...cells.map(r=>[`Page ${i}`,...r]))}if(!wb.SheetNames.length){XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['No selectable text was found. This PDF may be scanned.']]),'Read me')}const blob=new Blob([XLSX.write(wb,{bookType:'xlsx',type:'array'})],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});downloadBlob(blob,safeName(f.name)+'.xlsx');setStatus(`Done. Exported ${pdf.numPages} page(s). Check the workbook for columns and tables that may need cleanup. Scanned-page OCR is not included yet.`,'success')}
async function mergePdf(){const fs=Array.from($('#files').files||[]);if(fs.length<2)throw new Error('Choose at least two PDF files.');if(!window.PDFLib)throw new Error('PDF library did not load. Refresh and try again.');const out=await PDFLib.PDFDocument.create();for(let i=0;i<fs.length;i++){setStatus(`Adding PDF ${i+1} of ${fs.length}…`);const src=await PDFLib.PDFDocument.load(await fs[i].arrayBuffer());const pages=await out.copyPages(src,src.getPageIndices());pages.forEach(p=>out.addPage(p))}downloadBlob(new Blob([await out.save()],{type:'application/pdf'}),'merged-document.pdf');setStatus(`Merged ${fs.length} PDF files successfully.`,'success')}
async function splitPdf(){const f=getFile();if(!window.PDFLib)throw new Error('PDF library did not load. Refresh and try again.');const src=await PDFLib.PDFDocument.load(await f.arrayBuffer()),from=Number($('#from').value),to=Number($('#to').value);if(!Number.isInteger(from)||!Number.isInteger(to)||from<1||to<from||to>src.getPageCount())throw new Error(`Enter a valid range between page 1 and ${src.getPageCount()}.`);const out=await PDFLib.PDFDocument.create(),indices=Array.from({length:to-from+1},(_,i)=>from-1+i),pages=await out.copyPages(src,indices);pages.forEach(p=>out.addPage(p));downloadBlob(new Blob([await out.save()],{type:'application/pdf'}),`${safeName(f.name)}-pages-${from}-${to}.pdf`);setStatus(`Exported pages ${from}–${to}.`,'success')}
async function imagesToPdf(){const fs=Array.from($('#files').files||[]);if(!fs.length)throw new Error('Choose at least one JPG or PNG image.');if(!window.PDFLib)throw new Error('PDF library did not load. Refresh and try again.');const out=await PDFLib.PDFDocument.create();for(let i=0;i<fs.length;i++){const f=fs[i],bytes=await f.arrayBuffer();let img;if(f.type==='image/png')img=await out.embedPng(bytes);else if(f.type==='image/jpeg')img=await out.embedJpg(bytes);else throw new Error(`Unsupported image type: ${f.name}. Use JPG or PNG.`);const page=out.addPage([img.width,img.height]);page.drawImage(img,{x:0,y:0,width:img.width,height:img.height})}downloadBlob(new Blob([await out.save()],{type:'application/pdf'}),'images.pdf');setStatus(`Created a PDF from ${fs.length} image(s).`,'success')}
async function compressImage(){const f=getFile(),quality=Math.min(1,Math.max(.2,Number($('#quality').value)||.75)),maxW=Math.max(100,Number($('#maxwidth').value)||1600);if(!f.type.startsWith('image/'))throw new Error('Choose a valid image file.');const bitmap=await createImageBitmap(f),scale=Math.min(1,maxW/bitmap.width),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',quality));if(!blob)throw new Error('Could not compress this image.');downloadBlob(blob,safeName(f.name)+'-compressed.jpg');setStatus(`Done. Original: ${(f.size/1024).toFixed(0)} KB. Output: ${(blob.size/1024).toFixed(0)} KB. The output is JPEG, so transparent backgrounds become white.`,'success');bitmap.close()}
// A simple health check demonstrates the Cloudflare Pages Functions backend is deployed.
fetch('/api/health').then(r=>r.ok?r.json():null).then(data=>{if(data&&data.ok)document.documentElement.dataset.backend='online'}).catch(()=>{});
})();
